# -*- mode: ruby -*-
# vi: set ft=ruby :

load '~/token/creds.rb'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'digital_ocean'
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.provider :digital_ocean do |provider,  override|
    override.ssh.private_key_path = '~/.ssh/vagrant1'
    override.vm.box = 'digitalocean'
    #override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    provider.token = DO_TOKEN
    provider.image = "ubuntu-14-04-x64"
    provider.region = "nyc2"
    provider.size= '512mb'
  end

  config.vm.provision :shell, :path => "setup.sh"

end
